### ISSUE TITLE
催更！！！！！

### ISSUE THREAD

**Issue by xiaoshengjianan** [Sirius0v0/word-template-for-NPU-thesis#2]
楼主应该读硕士了，怎么不出个硕士毕业论文模板？？？

**Comment by Sirius0v0** [comment]
在做啦~

**Comment by xiaoshengjianan** [comment]
摸摸叽



---原始邮件---
发件人: "Jonny ***@***.***&gt;
发送时间: 2024年1月27日(周六) 下午3:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Sirius0v0/word-template-for-NPU-thesis] 催更！！！！！ (Issue #2)




 
在做啦~
